name: Android test and alpha update

on:
  push:
    branches: [ envoy-demo, hc-demo ]

jobs:
  build_alpha:
    runs-on: ubuntu-latest
    steps:
    - name: Do checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Check for missing qq strings
      run: ./scripts/missing-qq.py
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Clean and build
      env:
        DNSTT_SERVER: ${{ secrets.DNSTT_SERVER }}
        DNSTT_KEY: ${{ secrets.DNSTT_KEY }}
        DNSTT_PATH: ${{ secrets.DNSTT_PATH }}
        DOH_URL: ${{ secrets.DOH_URL }}
        DEF_PROXY: ${{ secrets.DEF_PROXY }}
      run: ./gradlew clean assembleRelease --stacktrace -Pdnsttserver=$DNSTT_SERVER -Pdnsttkey=$DNSTT_KEY -Pdnsttpath=$DNSTT_PATH -PdohUrl=$DOH_URL -PdefProxy=$DEF_PROXY
    - name: List
      run: ls -alR ./app/build/outputs/apk/
    - uses: r0adkll/sign-android-release@v1
      name: Sign APK
      id: build_signed
      with:
        releaseDirectory: app/build/outputs/apk/alpha/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    - name: Create hash
      run: git rev-parse HEAD > app/build/outputs/apk/alpha/release/rev-hash.txt
    - name: Rename APK to universal
      run: mv app/build/outputs/apk/alpha/release/app-alpha-release-signed.apk app/build/outputs/apk/alpha/release/app-alpha-universal-release.apk
    - uses: dev-drprasad/delete-tag-and-release@v0.1.2
      name: Delete latest alpha tag
      with:
        delete_release: false
        tag_name: latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      name: Create release and upload artifacts
      with:
        name: latest
        commit: main
        tag: latest
        artifacts: "app/build/outputs/apk/alpha/release/app-alpha-universal-release.apk,app/build/outputs/apk/alpha/release/rev-hash.txt"
        body: This is the latest version of the app (autogenerated).
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        replacesArtifacts: true
