name: update wiki unblocked release

on:
  push:
    branches: [ wiki-unblocked, wiki-unblocked-actions, envoy-demo, hc-demo ]

jobs:
  build_release:
    runs-on: ubuntu-latest
    steps:
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10
    - name: Do checkout
      uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Check for missing qq strings
      run: ./scripts/missing-qq.py
    - name: Checkout submodules
      run: git submodule update --init --recursive
    - name: Clean and build
      env:
        DNSTT_DOMAIN: ${{ secrets.DNSTT_SERVER }}
        DNSTT_KEY: ${{ secrets.DNSTT_KEY }}
        DNSTT_PATH: ${{ secrets.DNSTT_PATH }}
        DOH_URL: ${{ secrets.DOH_URL }}
        DEF_PROXY: ${{ secrets.DEF_PROXY }}
        HYST_CERT: ${{ secrets.HYST_CERT }}
      run: ./gradlew clean assembleFullGfdroidRelease --stacktrace -Pdnsttdomain=$DNSTT_DOMAIN -Pdnsttkey=$DNSTT_KEY -Pdnsttpath=$DNSTT_PATH -PdohUrl=$DOH_URL -PdefProxy=$DEF_PROXY -PhystCert=$HYST_CERT
    - name: List
      run: ls -alR ./app/build/outputs/apk/
    - uses: r0adkll/sign-android-release@v1
      name: Sign APK
      id: build_signed
      with:
        releaseDirectory: app/build/outputs/apk/greatfire/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.SIGNING_KEY_ALIAS }}
        keyStorePassword: ${{ secrets.SIGNING_STORE_PASSWORD }}
        keyPassword: ${{ secrets.SIGNING_KEY_PASSWORD }}
    - name: Create hash
      run: git rev-parse HEAD > app/build/outputs/apk/greatfire/release/rev-hash.txt
    - name: Rename APK to universal
      run: mv app/build/outputs/apk/greatfire/release/app-greatfire-release-unsigned-signed.apk app/build/outputs/apk/greatfire/release/app-greatfire-universal-release.apk
    - uses: dev-drprasad/delete-tag-and-release@v0.1.2
      name: Delete previous release tag
      with:
        delete_release: false
        tag_name: envoy-latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - uses: ncipollo/release-action@v1
      name: Create release and upload artifacts
      with:
        name: wiki-unblocked
        commit: ${{ github.sha }}
        tag: envoy-latest
        artifacts: "app/build/outputs/apk/greatfire/release/app-greatfire-universal-release.apk,app/build/outputs/apk/greatfire/release/rev-hash.txt"
        body: This is an android release automatically built from the latest commit to the wiki-unblocked branch.
        token: ${{ secrets.GITHUB_TOKEN }}
        allowUpdates: true
        replacesArtifacts: true
